version: "3"
services:
  app:
    image: python:3.8-slim
    working_dir: /app
    volumes:
      - ./app:/app
      - ./requirements.txt:/app/requirements.txt
    ports:
      - "9001:5002"
    entrypoint: /bin/sh -c "pip install -r requirements.txt && python app.py"
